-- Schema completo do Synfonia para INSTALAÇÃO NOVA (banco vazio).
-- Já inclui o efeito de todas as migrations de 2026-10-07 (comunidade, rbac, mongo_para_postgres);
-- rodá-las depois é seguro (são idempotentes), mas desnecessário.
-- Para atualizar um banco que já existe, NÃO use este arquivo: rode só as migrations datadas (ver LEIA-ME.md).
--
-- Gerado com: pg_dump --schema-only --no-owner --no-privileges

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: album_ratings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.album_ratings (
    id character varying(64) NOT NULL,
    album_key character varying(512) NOT NULL,
    album_name text,
    artista text,
    atualizado_em timestamp(6) without time zone,
    capa_url text,
    criado_em timestamp(6) without time zone,
    nota double precision,
    oculto boolean,
    oculto_em timestamp(6) without time zone,
    oculto_motivo character varying(500),
    oculto_por bigint,
    review text,
    source character varying(32),
    titulo character varying(200),
    user_id bigint NOT NULL,
    CONSTRAINT album_ratings_source_check CHECK (((source)::text = ANY ((ARRAY['SPOTIFY'::character varying, 'ITUNES'::character varying, 'YOUTUBE_MUSIC'::character varying])::text[])))
);


--
-- Name: auditoria_moderacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auditoria_moderacao (
    id bigint NOT NULL,
    acao character varying(64) NOT NULL,
    alvo_id character varying(64),
    alvo_tipo character varying(32),
    alvo_usuario_id bigint,
    ator_id bigint,
    criado_em timestamp(6) without time zone NOT NULL,
    detalhe text,
    motivo character varying(500)
);


--
-- Name: auditoria_moderacao_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auditoria_moderacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_moderacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historico_reproducao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historico_reproducao (
    id character varying(64) NOT NULL,
    data_reproducao timestamp(6) without time zone,
    track_id character varying(128) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: musicas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.musicas (
    id character varying(128) NOT NULL,
    album text,
    ano_lancamento integer,
    artista text,
    capa_url text,
    nome text,
    preview_url text,
    source character varying(32),
    uri text,
    CONSTRAINT musicas_source_check CHECK (((source)::text = ANY ((ARRAY['SPOTIFY'::character varying, 'ITUNES'::character varying, 'YOUTUBE_MUSIC'::character varying])::text[])))
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    data_expiracao timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: playlist_tracks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.playlist_tracks (
    playlist_id character varying(64) NOT NULL,
    track_id character varying(128) NOT NULL,
    posicao integer NOT NULL
);


--
-- Name: playlists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.playlists (
    id character varying(64) NOT NULL,
    bloqueada_moderacao boolean,
    bloqueio_motivo character varying(500),
    capa_url text,
    nome text,
    publico boolean NOT NULL,
    spotify_playlist_id character varying(128),
    sync_spotify boolean NOT NULL,
    user_id bigint NOT NULL,
    vibe character varying(64)
);


--
-- Name: user_songs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_songs (
    id character varying(64) NOT NULL,
    album_name text,
    artist_name text,
    data_adicao timestamp(6) without time zone,
    source character varying(32),
    track_id character varying(128) NOT NULL,
    track_name text,
    user_id bigint NOT NULL,
    CONSTRAINT user_songs_source_check CHECK (((source)::text = ANY ((ARRAY['SPOTIFY'::character varying, 'ITUNES'::character varying, 'YOUTUBE_MUSIC'::character varying])::text[])))
);


--
-- Name: usuario_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_roles (
    usuario_id bigint NOT NULL,
    role character varying(32) NOT NULL,
    CONSTRAINT usuario_roles_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'MODERATOR'::character varying, 'ADMIN'::character varying, 'SUPER_ADMIN'::character varying])::text[])))
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    banido boolean DEFAULT false,
    banido_ate timestamp(6) without time zone,
    banido_motivo character varying(500),
    bloqueado_ate timestamp(6) without time zone,
    data_criacao timestamp(6) without time zone,
    data_desativacao timestamp(6) without time zone,
    display_name character varying(255),
    email character varying(255) NOT NULL,
    favorite_track_artist character varying(255),
    favorite_track_capa_url character varying(255),
    favorite_track_id character varying(255),
    favorite_track_name character varying(255),
    favorite_track_preview_url character varying(255),
    foto_perfil text,
    instagram_link character varying(255),
    papel smallint NOT NULL,
    perfil_publico boolean DEFAULT true,
    nome_completo character varying(255) NOT NULL,
    preferred_music_source character varying(255),
    senha character varying(255) NOT NULL,
    show_avaliacoes boolean DEFAULT true,
    show_curtidas boolean DEFAULT true,
    show_personal_name boolean DEFAULT true,
    show_spotify_activity boolean DEFAULT true,
    spotify_link character varying(255),
    tentativas_falhas integer,
    ultimo_login timestamp(6) without time zone,
    username character varying(255) NOT NULL,
    username_changed boolean,
    youtube_link character varying(255),
    CONSTRAINT usuarios_papel_check CHECK (((papel >= 0) AND (papel <= 1))),
    CONSTRAINT usuarios_preferred_music_source_check CHECK (((preferred_music_source)::text = ANY ((ARRAY['SPOTIFY'::character varying, 'ITUNES'::character varying, 'YOUTUBE_MUSIC'::character varying])::text[])))
);


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ytmusic_credentials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ytmusic_credentials (
    usuario_id bigint NOT NULL,
    access_token text NOT NULL,
    expires_at bigint NOT NULL,
    refresh_token text NOT NULL,
    scope character varying(255),
    token_type character varying(255)
);


--
-- Name: album_ratings album_ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.album_ratings
    ADD CONSTRAINT album_ratings_pkey PRIMARY KEY (id);


--
-- Name: auditoria_moderacao auditoria_moderacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria_moderacao
    ADD CONSTRAINT auditoria_moderacao_pkey PRIMARY KEY (id);


--
-- Name: historico_reproducao historico_reproducao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_reproducao
    ADD CONSTRAINT historico_reproducao_pkey PRIMARY KEY (id);


--
-- Name: musicas musicas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.musicas
    ADD CONSTRAINT musicas_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: playlist_tracks playlist_tracks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playlist_tracks
    ADD CONSTRAINT playlist_tracks_pkey PRIMARY KEY (playlist_id, posicao);


--
-- Name: playlists playlists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playlists
    ADD CONSTRAINT playlists_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: album_ratings uk_album_ratings_usuario_album; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.album_ratings
    ADD CONSTRAINT uk_album_ratings_usuario_album UNIQUE (user_id, album_key);


--
-- Name: usuarios uk_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT uk_email UNIQUE (email);


--
-- Name: historico_reproducao uk_historico_usuario_faixa; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_reproducao
    ADD CONSTRAINT uk_historico_usuario_faixa UNIQUE (user_id, track_id);


--
-- Name: user_songs uk_user_songs_usuario_faixa; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_songs
    ADD CONSTRAINT uk_user_songs_usuario_faixa UNIQUE (user_id, track_id);


--
-- Name: usuarios ukm2dvbwfge291euvmk6vkkocao; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukm2dvbwfge291euvmk6vkkocao UNIQUE (username);


--
-- Name: password_reset_tokens uknmq2xlhxauheilqejd5py9xx8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uknmq2xlhxauheilqejd5py9xx8 UNIQUE (usuario_id);


--
-- Name: user_songs user_songs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_songs
    ADD CONSTRAINT user_songs_pkey PRIMARY KEY (id);


--
-- Name: usuario_roles usuario_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT usuario_roles_pkey PRIMARY KEY (usuario_id, role);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: ytmusic_credentials ytmusic_credentials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ytmusic_credentials
    ADD CONSTRAINT ytmusic_credentials_pkey PRIMARY KEY (usuario_id);


--
-- Name: idx_album_ratings_usuario_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_album_ratings_usuario_data ON public.album_ratings USING btree (user_id, atualizado_em);


--
-- Name: idx_auditoria_alvo_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_alvo_usuario ON public.auditoria_moderacao USING btree (alvo_usuario_id);


--
-- Name: idx_auditoria_criado_em; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_criado_em ON public.auditoria_moderacao USING btree (criado_em);


--
-- Name: idx_historico_usuario_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historico_usuario_data ON public.historico_reproducao USING btree (user_id, data_reproducao);


--
-- Name: idx_musicas_artista; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_musicas_artista ON public.musicas USING btree (artista);


--
-- Name: idx_musicas_nome; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_musicas_nome ON public.musicas USING btree (nome);


--
-- Name: idx_playlists_user_publico; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_playlists_user_publico ON public.playlists USING btree (user_id, publico);


--
-- Name: idx_user_songs_usuario_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_songs_usuario_data ON public.user_songs USING btree (user_id, data_adicao);


--
-- Name: idx_usuarios_username_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_username_lower ON public.usuarios USING btree (lower((username)::text));


--
-- Name: album_ratings fk_album_ratings_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.album_ratings
    ADD CONSTRAINT fk_album_ratings_usuario FOREIGN KEY (user_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: historico_reproducao fk_historico_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_reproducao
    ADD CONSTRAINT fk_historico_usuario FOREIGN KEY (user_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: password_reset_tokens fk_password_reset_tokens_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fk_password_reset_tokens_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: playlist_tracks fk_playlist_tracks_playlist; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playlist_tracks
    ADD CONSTRAINT fk_playlist_tracks_playlist FOREIGN KEY (playlist_id) REFERENCES public.playlists(id) ON DELETE CASCADE;


--
-- Name: playlists fk_playlists_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playlists
    ADD CONSTRAINT fk_playlists_usuario FOREIGN KEY (user_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: user_songs fk_user_songs_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_songs
    ADD CONSTRAINT fk_user_songs_usuario FOREIGN KEY (user_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: usuario_roles fk_usuario_roles_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fk_usuario_roles_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: ytmusic_credentials fk_ytmusic_credentials_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ytmusic_credentials
    ADD CONSTRAINT fk_ytmusic_credentials_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


